from pydantic import BaseModel, Field
from typing import List, Optional
from app.schemas.risk_evidence import RiskEvidence
from app.schemas.ai_response import AIResponse
from app.schemas.verified_response import VerificationResult, VerifiedResponse
from app.schemas.claims import Claim, Citation

class WorkflowState(BaseModel):
    """
    Complete state representation for the LangGraph AI workflow.
    """
    # Request Metadata
    request_id: str = Field(..., description="Unique identifier for the request.")
    identity_id: str = Field(..., description="The identity ARN or UUID being investigated.")
    workspace_id: str = Field(..., description="The workspace ID context.")
    
    # Execution Metadata
    node_history: List[str] = Field(default_factory=list, description="List of nodes visited during execution.")
    retry_count: int = Field(default=0, description="Number of retries attempted in the current workflow loop.")
    start_time: Optional[float] = Field(None, description="Workflow start timestamp.")
    
    # AI Generation Metrics
    generation_started_at: Optional[float] = Field(None, description="Timestamp when AI generation started.")
    generation_completed_at: Optional[float] = Field(None, description="Timestamp when AI generation completed.")
    latency_ms: Optional[float] = Field(None, description="AI generation latency in milliseconds.")
    provider_name: Optional[str] = Field(None, description="AI provider used for generation.")
    model_name: Optional[str] = Field(None, description="AI model used for generation.")
    prompt_version: Optional[str] = Field(None, description="Version of the prompt template used.")
    estimated_token_usage: Optional[int] = Field(None, description="Estimated tokens used during generation.")
    
    # Workflow Data
    evidence: Optional[RiskEvidence] = Field(None, description="Evidence collected for the investigation.")
    ai_draft: Optional[AIResponse] = Field(None, description="Draft response generated by the AI analyst.")
    
    # Verification & Explainability
    extracted_claims: List[Claim] = Field(default_factory=list, description="Factual claims extracted from the AI draft.")
    verification_results: List[VerificationResult] = Field(default_factory=list, description="Results of the verification process.")
    confidence_score: float = Field(default=0.0, description="Calculated confidence score based on verification.")
    citations: List[Citation] = Field(default_factory=list, description="List of citations and references to evidence.")
    
    # Final Output
    final_response: Optional[VerifiedResponse] = Field(None, description="The final, verified response.")
    error_message: Optional[str] = Field(None, description="Any unrecoverable error encountered.")
