"""Add CanonicalEvent model

Revision ID: 062e7b7c3a52
Revises: a1b2c3d4e5f6
Create Date: 2026-07-14 14:55:25.107499

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '062e7b7c3a52'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('canonical_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('source_tool', sa.String(length=100), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('severity_raw', sa.String(length=50), nullable=True),
    sa.Column('severity_normalized', sa.Integer(), nullable=True),
    sa.Column('timestamp_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actor_identifier', sa.String(length=512), nullable=True),
    sa.Column('asset_identifier', sa.String(length=512), nullable=True),
    sa.Column('raw_event_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('linked_access_log_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_canonical_event_time_actor', 'canonical_events', ['timestamp_utc', 'actor_identifier'], unique=False)
    op.create_index(op.f('ix_canonical_events_actor_identifier'), 'canonical_events', ['actor_identifier'], unique=False)
    op.create_index(op.f('ix_canonical_events_asset_identifier'), 'canonical_events', ['asset_identifier'], unique=False)
    op.create_index(op.f('ix_canonical_events_event_type'), 'canonical_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_canonical_events_linked_access_log_id'), 'canonical_events', ['linked_access_log_id'], unique=False)
    op.create_index(op.f('ix_canonical_events_source_tool'), 'canonical_events', ['source_tool'], unique=False)
    op.create_index(op.f('ix_canonical_events_timestamp_utc'), 'canonical_events', ['timestamp_utc'], unique=False)
    op.create_index(op.f('ix_canonical_events_workspace_id'), 'canonical_events', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_canonical_events_workspace_id'), table_name='canonical_events')
    op.drop_index(op.f('ix_canonical_events_timestamp_utc'), table_name='canonical_events')
    op.drop_index(op.f('ix_canonical_events_source_tool'), table_name='canonical_events')
    op.drop_index(op.f('ix_canonical_events_linked_access_log_id'), table_name='canonical_events')
    op.drop_index(op.f('ix_canonical_events_event_type'), table_name='canonical_events')
    op.drop_index(op.f('ix_canonical_events_asset_identifier'), table_name='canonical_events')
    op.drop_index(op.f('ix_canonical_events_actor_identifier'), table_name='canonical_events')
    op.drop_index('idx_canonical_event_time_actor', table_name='canonical_events')
    op.drop_table('canonical_events')
    # ### end Alembic commands ###
