"""add error and findings to job

Revision ID: ab2cf4492ad0
Revises: c4f359d476fa
Create Date: 2026-07-15 15:39:38.750113

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab2cf4492ad0'
down_revision: Union[str, Sequence[str], None] = 'c4f359d476fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ingestion_jobs', sa.Column('error_message', sa.String(length=1024), nullable=True))
    op.add_column('ingestion_jobs', sa.Column('risk_findings_generated', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ingestion_jobs', 'risk_findings_generated')
    op.drop_column('ingestion_jobs', 'error_message')
    # ### end Alembic commands ###
