"""Add workspace_id to models

Revision ID: b8017f7e72ff
Revises: c1070c4aaa00
Create Date: 2026-07-01 16:08:33.908537

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8017f7e72ff'
down_revision: Union[str, Sequence[str], None] = 'c1070c4aaa00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Add columns as nullable=True first
    op.add_column('access_logs', sa.Column('workspace_id', sa.UUID(), nullable=True))
    op.add_column('ingestion_jobs', sa.Column('workspace_id', sa.UUID(), nullable=True))
    op.add_column('machine_identities', sa.Column('workspace_id', sa.UUID(), nullable=True))
    op.add_column('risk_findings', sa.Column('workspace_id', sa.UUID(), nullable=True))
    op.add_column('risk_scores', sa.Column('workspace_id', sa.UUID(), nullable=True))
    
    # Get or create a default organization and workspace to assign existing data
    conn = op.get_bind()
    
    # Check if we have any workspace
    res = conn.execute(sa.text("SELECT id FROM workspaces LIMIT 1")).fetchone()
    if res:
        default_workspace_id = res[0]
    else:
        # Create default org and workspace
        import uuid
        org_id = uuid.uuid4()
        default_workspace_id = uuid.uuid4()
        conn.execute(sa.text("INSERT INTO organizations (id, name, slug) VALUES (:id, 'Default Org', 'default-org')"), {"id": org_id})
        conn.execute(sa.text("INSERT INTO workspaces (id, organization_id, name) VALUES (:id, :org_id, 'Default Workspace')"), {"id": default_workspace_id, "org_id": org_id})
        
    # Update existing rows
    conn.execute(sa.text("UPDATE access_logs SET workspace_id = :wid"), {"wid": default_workspace_id})
    conn.execute(sa.text("UPDATE ingestion_jobs SET workspace_id = :wid"), {"wid": default_workspace_id})
    conn.execute(sa.text("UPDATE machine_identities SET workspace_id = :wid"), {"wid": default_workspace_id})
    conn.execute(sa.text("UPDATE risk_findings SET workspace_id = :wid"), {"wid": default_workspace_id})
    conn.execute(sa.text("UPDATE risk_scores SET workspace_id = :wid"), {"wid": default_workspace_id})
    
    # Alter columns to nullable=False
    op.alter_column('access_logs', 'workspace_id', nullable=False)
    op.alter_column('ingestion_jobs', 'workspace_id', nullable=False)
    op.alter_column('machine_identities', 'workspace_id', nullable=False)
    op.alter_column('risk_findings', 'workspace_id', nullable=False)
    op.alter_column('risk_scores', 'workspace_id', nullable=False)

    # Add indexes and foreign keys
    op.create_index(op.f('ix_access_logs_workspace_id'), 'access_logs', ['workspace_id'], unique=False)
    op.create_foreign_key('fk_access_logs_workspace_id', 'access_logs', 'workspaces', ['workspace_id'], ['id'], ondelete='CASCADE')
    
    op.create_index(op.f('ix_ingestion_jobs_workspace_id'), 'ingestion_jobs', ['workspace_id'], unique=False)
    op.create_foreign_key('fk_ingestion_jobs_workspace_id', 'ingestion_jobs', 'workspaces', ['workspace_id'], ['id'], ondelete='CASCADE')
    op.drop_column('ingestion_jobs', 'tenant_id')
    
    op.create_index(op.f('ix_machine_identities_workspace_id'), 'machine_identities', ['workspace_id'], unique=False)
    op.create_foreign_key('fk_machine_identities_workspace_id', 'machine_identities', 'workspaces', ['workspace_id'], ['id'], ondelete='CASCADE')
    
    op.create_index(op.f('ix_risk_findings_workspace_id'), 'risk_findings', ['workspace_id'], unique=False)
    op.create_foreign_key('fk_risk_findings_workspace_id', 'risk_findings', 'workspaces', ['workspace_id'], ['id'], ondelete='CASCADE')
    
    op.create_index(op.f('ix_risk_scores_workspace_id'), 'risk_scores', ['workspace_id'], unique=False)
    op.create_foreign_key('fk_risk_scores_workspace_id', 'risk_scores', 'workspaces', ['workspace_id'], ['id'], ondelete='CASCADE')


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_risk_scores_workspace_id', 'risk_scores', type_='foreignkey')
    op.drop_index(op.f('ix_risk_scores_workspace_id'), table_name='risk_scores')
    op.drop_column('risk_scores', 'workspace_id')
    op.drop_constraint('fk_risk_findings_workspace_id', 'risk_findings', type_='foreignkey')
    op.drop_index(op.f('ix_risk_findings_workspace_id'), table_name='risk_findings')
    op.drop_column('risk_findings', 'workspace_id')
    op.drop_constraint('fk_machine_identities_workspace_id', 'machine_identities', type_='foreignkey')
    op.drop_index(op.f('ix_machine_identities_workspace_id'), table_name='machine_identities')
    op.drop_column('machine_identities', 'workspace_id')
    op.add_column('ingestion_jobs', sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint('fk_ingestion_jobs_workspace_id', 'ingestion_jobs', type_='foreignkey')
    op.drop_index(op.f('ix_ingestion_jobs_workspace_id'), table_name='ingestion_jobs')
    op.drop_column('ingestion_jobs', 'workspace_id')
    op.drop_constraint('fk_access_logs_workspace_id', 'access_logs', type_='foreignkey')
    op.drop_index(op.f('ix_access_logs_workspace_id'), table_name='access_logs')
    op.drop_column('access_logs', 'workspace_id')
    # ### end Alembic commands ###
