"""stage 4 updates

Revision ID: c4f359d476fa
Revises: 062e7b7c3a52
Create Date: 2026-07-15 15:38:57.000791

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c4f359d476fa'
down_revision: Union[str, Sequence[str], None] = '062e7b7c3a52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('criticality_configs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('asset_id', sa.String(length=512), nullable=False),
    sa.Column('criticality', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'asset_id', name='uq_workspace_asset')
    )
    op.create_index(op.f('ix_criticality_configs_asset_id'), 'criticality_configs', ['asset_id'], unique=False)
    op.create_index(op.f('ix_criticality_configs_workspace_id'), 'criticality_configs', ['workspace_id'], unique=False)
    op.add_column('risk_scores', sa.Column('legacy_comparison_score', sa.Integer(), nullable=True))
    op.add_column('risk_scores', sa.Column('risk_evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('risk_scores', 'risk_evidence')
    op.drop_column('risk_scores', 'legacy_comparison_score')
    op.drop_index(op.f('ix_criticality_configs_workspace_id'), table_name='criticality_configs')
    op.drop_index(op.f('ix_criticality_configs_asset_id'), table_name='criticality_configs')
    op.drop_table('criticality_configs')
    # ### end Alembic commands ###
