from pydantic import BaseModel, Field
from typing import List, Optional

class Finding(BaseModel):
    title: str = Field(..., description="Title of the security finding.")
    description: str = Field(..., description="Detailed description of the finding.")
    severity: str = Field(..., description="Severity of the finding (e.g., Low, Medium, High, Critical).")
    affected_resource: Optional[str] = Field(None, description="The resource affected by this finding.")

class Recommendation(BaseModel):
    action: str = Field(..., description="The recommended action to take.")
    rationale: str = Field(..., description="Why this action is recommended.")
    effort: str = Field(..., description="Estimated effort to implement (e.g., Low, Medium, High).")

class AIResponse(BaseModel):
    """
    Enterprise contract for the structured response generated by the AI Analyst.
    Provides a predictable schema for downstream consumers.
    """
    executive_summary: str = Field(..., description="High-level summary of the investigation.")
    risk_assessment: str = Field(..., description="Detailed assessment of the identity's risk profile.")
    attack_path_analysis: str = Field(..., description="Analysis of potential lateral movement and blast radius.")
    findings: List[Finding] = Field(default_factory=list, description="Specific security findings discovered.")
    recommendations: List[Recommendation] = Field(default_factory=list, description="Actionable recommendations for remediation.")
    success: bool = Field(default=True, description="Whether the AI analysis was successful.")
    code: Optional[str] = Field(None, description="Error code if the analysis failed.")
    message: Optional[str] = Field(None, description="Error message if the analysis failed.")
