from pydantic import BaseModel, Field
from typing import List, Optional
from app.schemas.ai_response import AIResponse
from app.schemas.claims import Citation

class VerificationResult(BaseModel):
    claim: str = Field(..., description="The specific factual claim extracted from the AI response.")
    is_verified: bool = Field(..., description="Whether the claim is supported by the evidence.")
    evidence_reference: Optional[str] = Field(None, description="Reference to the specific evidence supporting or refuting the claim.")
    correction: Optional[str] = Field(None, description="Corrected claim if the original was found to be a hallucination.")

class VerifiedResponse(BaseModel):
    """
    Enterprise contract for an AI response that has passed through a verification layer.
    Ensures that factual claims in the AI response have been checked against ground-truth evidence.
    """
    original_response: AIResponse = Field(..., description="The original structured response generated by the AI.")
    verifications: List[VerificationResult] = Field(default_factory=list, description="List of verification checks performed on the response.")
    is_fully_verified: bool = Field(..., description="True if all factual claims were verified successfully.")
    confidence_score: float = Field(..., description="A confidence score between 0.0 and 1.0 based on verification results.")
    citations: List[Citation] = Field(default_factory=list, description="Structured citations mapping verified claims back to evidence sources.")
    final_response: AIResponse = Field(..., description="The final response after any hallucinated claims have been corrected or removed.")

